spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///eblog
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

